name: "Fastlane scan - iOS"
on:
  workflow_dispatch

jobs:
  run_tests:
    runs-on: macos-11
    steps:
      - name: Install xcbeautify if needed
        run: brew install xcbeautify

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Test on iOS Devices
        run:  |
          bundle update
          bundle exec fastlane scan

      - name: Get the bundle result
        uses: actions/upload-artifact@v3
        with:
          name: Test-result.xcresult
          path: fastlane/test_output/ExampleProject.xcresult