name: "Fastlane scan - iOS"
on:
  workflow_dispatch

jobs:
  run_tests:
    runs-on: macos-11
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test on iOS Devices
        run:  |
        bundle update
        bundle exec fastlane scan