name: "Test on iOS"
env:
  PROJECT_NAME: ExampleProject
  TEST_TARGET: SimpleCalculatorTests
on:
  push
  workflow_dispatch:
    inputs:
      target:
        description: 'iPhone Model'
        required: false
        default: 'iPhone 8'
        type: choice
        options:
        - iPod touch (7th generation)
        - iPad mini (6th generation)
        - iPad (7th generation)
        - iPad (8th generation)
        - iPhone 8
        - iPhone 11
        - iPhone 11 Pro
        - iPhone 12
        - iPhone 12 Pro
        - iPhone 13
        - iPhone 13 Pro

jobs:
  run_tests:
    runs-on: macos-11
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test on ${{ github.event.inputs.target }} - iOS 15.2
        run: xcodebuild test -scheme ${{ env.PROJECT_NAME }} -project ${{ env.PROJECT_NAME }}.xcodeproj -only-testing ${{ env.TEST_TARGET }}/${{ env.TEST_TARGET }} -destination 'platform=iOS Simulator,name=${{ github.event.inputs.target }},OS=15.2' | xcpretty && exit ${PIPESTATUS[0]}